---
- include: createsystemusers.yml
- include: awsconfig.yml
- include: installtools.yml
- include: jenkinsdeploy.yml
  tags: [ codedeploy, merge ]
- include: configjks.yml
  tags: [ codedeploy, merge ]